version: '3.7'

services:
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - .env
    volumes:
    - static_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  django:
    build: ./django
    restart: always
    env_file:
      - .env
    volumes:
    - static_data:/vol/django
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    restart: always
    env_file:
      - .env
    volumes:
    - static_data:/vol/nginx
    ports:
      - "80:80"
      - "443:443"

volumes:
  static_data: